apiVersion: v1
kind: Secret
metadata:
  name: log-monitoring-secrets
  namespace: log-monitoring
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "admin123"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "admin123"
